# config.yml

# Site settings
title: Christina Joice
description: Senior Quality Assurance Engineer
baseurl: "" # the subpath of your site, e.g. "/blog"
url: "https://christinajoice.github.io" # the base hostname & protocol for your site
author: 
  name: ChristinaJoice
  email: christinallrejoice@gmail.com

# Theme settings
theme: awesome-jekyll-theme
